export enum ErrorCodes {
  ERROR_VERIFYING_ID_TOKEN = 100,
  NO_BEARER_TOKEN_PROVIDED = 101,
  INVALID_BEARER_TOKEN = 102,
  // CRUD BASED
  ERROR_ADDING_MODEL_DATA = 103,
  ERROR_GETTING_MODEL_DATA = 104,
  ERROR_UPDATING_MODEL_DATA = 105,
  ERROR_DELETING_MODEL_DATA = 106,
  NOT_FOUND_MODEL_DATA = 107,
  ACCESS_DENIED  = 108,
  INVALID_MONGO_OBJECT_ID = 109,

  NO_FILE_UPLOADED  = 110,
  INVALID_FILE_TYPE = 111,
  FILE_TOO_LARGE = 112,
  FILE_NOT_FOUND = 113,
  INVALID_FILE_PATH = 114,

  CANT_DELETE_MODEL_DATA = 115,

  MODEL_DATA_NOT_FOUND_BY_THIS_ID = 116
}


