export enum ErrorCodes {
  ERROR_VERIFYING_ID_TOKEN = 100,
  NO_BEARER_TOKEN_PROVIDED = 101,
  INVALID_BEARER_TOKEN = 102,
  // CRUD BASED
  ERROR_ADDING_MODEL_DATA = 103,
  ERROR_GETTING_MODEL_DATA = 104,
  ERROR_UPDATING_MODEL_DATA = 105,
  ERROR_DELETING_MODEL_DATA = 106,
  NOT_FOUND_MODEL_DATA = 107,

  ACCESS_DENIED  = 108
}


