version: '3.8'

services:
  app:
    container_name: dynamics-market-backend
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - '5000:5000'
    volumes:
      - ./uploads:/usr/src/app/uploads
