version: '3.8'

services:
  app:
    container_name: dynamics-market-backend
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - '5000:5000'
    volumes:
      - ./uploads:/usr/src/app/uploads
    depends_on:
      - redis
      - mongodb-primary
      - mongodb-secondary1
      - mongodb-secondary2

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  mongodb-primary:
    image: mongo:6.0
    container_name: mongodb-primary
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb_primary_data:/data/db
    command: ['mongod', '--replSet', 'rs0', '--bind_ip_all']

  mongodb-secondary1:
    image: mongo:6.0
    container_name: mongodb-secondary1
    restart: always
    ports:
      - '27018:27017'
    volumes:
      - mongodb_secondary1_data:/data/db
    command: ['mongod', '--replSet', 'rs0', '--bind_ip_all']

  mongodb-secondary2:
    image: mongo:6.0
    container_name: mongodb-secondary2
    restart: always
    ports:
      - '27019:27017'
    volumes:
      - mongodb_secondary2_data:/data/db
    command: ['mongod', '--replSet', 'rs0', '--bind_ip_all']

volumes:
  redis_data:
  mongodb_primary_data:
  mongodb_secondary1_data:
  mongodb_secondary2_data:
