version: "3"
services:
  app:
    container_name: dynamics-market-backend
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - /home/${{ secrets.SERVER_USER }}/Projects/dynamics-market-backend/uploads:/usr/src/app/uploads
