services:
  app:
    container_name: dynamics-market-backend
    network_mode: host
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./uploads:/usr/src/app/uploads
    depends_on:
      - redis
      - elasticsearch

#  redis:
#    image: redis:latest
#    container_name: redis
#    network_mode: host
#    restart: always
#    volumes:
#      - redis_data:/data
#    command: redis-server --replicaof no one

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    network_mode: host
    container_name: elasticsearch
    environment:
      - node.name=es01
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - network.bind_host=127.0.0.1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    network_mode: host
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://127.0.0.1:9200
    depends_on:
      - elasticsearch

volumes:
#  redis_data:
  esdata: