name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: SSH to Server and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/Projects

            if [ ! -d "Projects/dynamics-market-backend" ]; then
              git clone https://github.com/farruhzoirov/dynamics-market-backend.git
            fi

            cd Projects/dynamics-market-backend
            git pull origin main

            # 🔹 .env faylni serverda yaratish
            echo "PORT=${{ secrets.PORT }}" > .env
            echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
            echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
            echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> .env

            docker stop dynamics-market-backend || true
            docker rm dynamics-market-backend || true
            docker build -t dynamics-market-backend .
            docker run -d --name dynamics-market-backend --env-file .env -p 5000:5000 --restart always -v /home/${{ secrets.SERVER_USER }}/Projects/dynamics-market-backend/uploads:/usr/src/app/uploads dynamics-market-backend