name: Deploy to VPS(Contabo)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: SSH to Server and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}

          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |

            if [ ! -d "dynamics-market-backend" ]; then
              rm -rf dynamics-market-backend
              git clone https://github.com/farruhzoirov/dynamics-market-backend.git
            fi


            cd dynamics-market-backend
            git reset --hard HEAD
            git pull origin main

            # 🔹 .env faylni yaratish
            cat > .env <<EOL
            PORT=${{ secrets.PORT }}
            MONGODB_URI=${{ secrets.MONGODB_URI }}
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
            EOL


            docker compose down
            docker-compose up -d --build
